root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/ssh ./cmd/ssh"
entrypoint = ["./tmp/ssh"]
include_ext = ["go"]
exclude_dir = ["tmp", "dist", ".ssh"]
exclude_unchanged = true
send_interrupt = true
delay = 200
