/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    'tracked-repositories': TrackedRepository;
    'oss-contributions': OSSContribution;
    'blog-posts': BlogPost;
    'project-stars': ProjectStar;
    'blog-stars': BlogStar;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'tracked-repositories': TrackedRepositoriesSelect<false> | TrackedRepositoriesSelect<true>;
    'oss-contributions': OssContributionsSelect<false> | OssContributionsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'project-stars': ProjectStarsSelect<false> | ProjectStarsSelect<true>;
    'blog-stars': BlogStarsSelect<false> | BlogStarsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'portfolio-settings': PortfolioSetting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'portfolio-settings': PortfolioSettingsSelect<false> | PortfolioSettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: {
      syncTrackedRepositories: TaskSyncTrackedRepositories;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  shortDescription: string;
  category: 'infrastructure' | 'developer-tools' | 'application' | 'open-source' | 'experiment' | 'other';
  overview: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        media: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  links?:
    | {
        label: string;
        url: string;
        type: 'github' | 'demo' | 'documentation' | 'package' | 'article' | 'custom';
        id?: string | null;
      }[]
    | null;
  topics?:
    | {
        name: string;
        slug: string;
        id?: string | null;
      }[]
    | null;
  status: 'active' | 'completed' | 'maintained' | 'archived' | 'experimental';
  accent?: ('blue' | 'cyan' | 'green' | 'yellow' | 'purple') | null;
  featured?: boolean | null;
  pinned?: boolean | null;
  displayOrder?: number | null;
  projectYear?: number | null;
  publishedAt?: string | null;
  repositoryOwner?: string | null;
  repositoryName?: string | null;
  /**
   * Optional search and social overrides. The project title, description, and cover image are used as fallbacks.
   */
  seo?: {
    /**
     * Aim for 50–60 characters and describe what the project does.
     */
    title?: string | null;
    /**
     * Aim for 140–160 characters with the main technology or outcome.
     */
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Add a GitHub repository once. Pull requests opened by the configured username are discovered and refreshed automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracked-repositories".
 */
export interface TrackedRepository {
  id: number;
  /**
   * Paste a repository URL like https://github.com/OneBusAway/maglev.
   */
  repositoryUrl: string;
  /**
   * Only pull requests opened by this GitHub account are imported.
   */
  githubUsername: string;
  /**
   * Automatic runs skip this repository until its cache expires.
   */
  syncIntervalHours: number;
  enabled?: boolean | null;
  /**
   * Bypasses the two-hour cache once when this document is saved.
   */
  refreshNow?: boolean | null;
  organization: string;
  repository: string;
  repoDescription?: string | null;
  stars?: number | null;
  discoveredPullRequests?: number | null;
  syncStatus: 'pending' | 'syncing' | 'synced' | 'error';
  nextSyncAt: string;
  lastSyncAttemptAt?: string | null;
  lastSyncedAt?: string | null;
  syncError?: string | null;
  githubRequestsLastSync?: number | null;
  githubRateLimitRemaining?: number | null;
  githubRateLimitResetAt?: string | null;
  repoKey: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pull requests are discovered from Tracked Repositories. GitHub facts stay synchronized while portfolio fields remain under your control.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oss-contributions".
 */
export interface OSSContribution {
  id: number;
  /**
   * Filled automatically for tracked repositories. A PR URL can still be imported manually as a fallback.
   */
  prUrl: string;
  /**
   * The repository tracker that discovered and refreshes this pull request.
   */
  trackedRepository?: (number | null) | TrackedRepository;
  /**
   * Bypasses the soumajitgh ownership check for co-authored or maintainer-opened PRs.
   */
  allowDifferentAuthor?: boolean | null;
  /**
   * Re-fetch factual metadata without changing your portfolio summary, tags, or visibility.
   */
  refreshFromGitHub?: boolean | null;
  /**
   * Explain your contribution and its impact. The PR title is used as the public fallback.
   */
  portfolioSummary?: string | null;
  tags?:
    | {
        name: string;
        slug: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  hidden?: boolean | null;
  displayOrder?: number | null;
  title: string;
  prNumber: number;
  author: string;
  status: 'open' | 'closed' | 'merged';
  prCreatedAt: string;
  mergedAt?: string | null;
  additions: number;
  deletions: number;
  changedFiles: number;
  prDescription?: string | null;
  organization: string;
  repository: string;
  repoUrl: string;
  repoDescription?: string | null;
  stars: number;
  githubSyncStatus: 'synced' | 'unavailable';
  githubSyncedAt: string;
  githubSyncError?: string | null;
  prKey: string;
  githubNodeId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * Generated from the title. Once published, changing it requires redirect support.
   */
  slug: string;
  /**
   * Permanently assigned from the atomic blog counter.
   */
  issueNumber: number;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional. When empty, a summary is generated from the article body.
   */
  excerpt?: string | null;
  labels?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  searchText?: string | null;
  readingMinutes: number;
  publishedAt?: string | null;
  /**
   * Show this post in the home page Blog tab.
   */
  featured?: boolean | null;
  /**
   * Optional search and social overrides. The article title and excerpt are used as fallbacks.
   */
  seo?: {
    /**
     * Aim for 50–60 characters and lead with the article topic.
     */
    title?: string | null;
    /**
     * Aim for 140–160 characters and summarize the practical value.
     */
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-stars".
 */
export interface ProjectStar {
  id: number;
  project: number | Project;
  visitorHash: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-stars".
 */
export interface BlogStar {
  id: number;
  blogPost: number | BlogPost;
  visitorHash: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  blogPosts?: {
    /**
     * Allow clients to find blog-posts.
     */
    find?: boolean | null;
    /**
     * Allow clients to create blog-posts.
     */
    create?: boolean | null;
    /**
     * Allow clients to update blog-posts.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete blog-posts.
     */
    delete?: boolean | null;
  };
  ossContributions?: {
    /**
     * Allow clients to find oss-contributions.
     */
    find?: boolean | null;
    /**
     * Allow clients to create oss-contributions.
     */
    create?: boolean | null;
    /**
     * Allow clients to update oss-contributions.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete oss-contributions.
     */
    delete?: boolean | null;
  };
  projects?: {
    /**
     * Allow clients to find projects.
     */
    find?: boolean | null;
    /**
     * Allow clients to create projects.
     */
    create?: boolean | null;
    /**
     * Allow clients to update projects.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete projects.
     */
    delete?: boolean | null;
  };
  trackedRepositories?: {
    /**
     * Allow clients to find tracked-repositories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create tracked-repositories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update tracked-repositories.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete tracked-repositories.
     */
    delete?: boolean | null;
  };
  portfolioSettings?: {
    /**
     * Allow clients to find portfolio-settings global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update portfolio-settings global.
     */
    update?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'syncTrackedRepositories';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'syncTrackedRepositories') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'tracked-repositories';
        value: number | TrackedRepository;
      } | null)
    | ({
        relationTo: 'oss-contributions';
        value: number | OSSContribution;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'project-stars';
        value: number | ProjectStar;
      } | null)
    | ({
        relationTo: 'blog-stars';
        value: number | BlogStar;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  category?: T;
  overview?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        media?: T;
        caption?: T;
        id?: T;
      };
  links?:
    | T
    | {
        label?: T;
        url?: T;
        type?: T;
        id?: T;
      };
  topics?:
    | T
    | {
        name?: T;
        slug?: T;
        id?: T;
      };
  status?: T;
  accent?: T;
  featured?: T;
  pinned?: T;
  displayOrder?: T;
  projectYear?: T;
  publishedAt?: T;
  repositoryOwner?: T;
  repositoryName?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracked-repositories_select".
 */
export interface TrackedRepositoriesSelect<T extends boolean = true> {
  repositoryUrl?: T;
  githubUsername?: T;
  syncIntervalHours?: T;
  enabled?: T;
  refreshNow?: T;
  organization?: T;
  repository?: T;
  repoDescription?: T;
  stars?: T;
  discoveredPullRequests?: T;
  syncStatus?: T;
  nextSyncAt?: T;
  lastSyncAttemptAt?: T;
  lastSyncedAt?: T;
  syncError?: T;
  githubRequestsLastSync?: T;
  githubRateLimitRemaining?: T;
  githubRateLimitResetAt?: T;
  repoKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oss-contributions_select".
 */
export interface OssContributionsSelect<T extends boolean = true> {
  prUrl?: T;
  trackedRepository?: T;
  allowDifferentAuthor?: T;
  refreshFromGitHub?: T;
  portfolioSummary?: T;
  tags?:
    | T
    | {
        name?: T;
        slug?: T;
        id?: T;
      };
  featured?: T;
  hidden?: T;
  displayOrder?: T;
  title?: T;
  prNumber?: T;
  author?: T;
  status?: T;
  prCreatedAt?: T;
  mergedAt?: T;
  additions?: T;
  deletions?: T;
  changedFiles?: T;
  prDescription?: T;
  organization?: T;
  repository?: T;
  repoUrl?: T;
  repoDescription?: T;
  stars?: T;
  githubSyncStatus?: T;
  githubSyncedAt?: T;
  githubSyncError?: T;
  prKey?: T;
  githubNodeId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  issueNumber?: T;
  body?: T;
  excerpt?: T;
  labels?:
    | T
    | {
        name?: T;
        id?: T;
      };
  searchText?: T;
  readingMinutes?: T;
  publishedAt?: T;
  featured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-stars_select".
 */
export interface ProjectStarsSelect<T extends boolean = true> {
  project?: T;
  visitorHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-stars_select".
 */
export interface BlogStarsSelect<T extends boolean = true> {
  blogPost?: T;
  visitorHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  blogPosts?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  ossContributions?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  projects?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  trackedRepositories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  portfolioSettings?:
    | T
    | {
        find?: T;
        update?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-settings".
 */
export interface PortfolioSetting {
  id: number;
  heroCommand: string;
  heroHeadline: string;
  heroDescription: string;
  /**
   * PDF downloaded by the Resume button on the home page.
   */
  resumeFile?: (number | null) | Media;
  contact: {
    /**
     * Public contact address and fallback form recipient. CONTACT_TO_EMAIL overrides delivery.
     */
    email: string;
    intro: string;
    socials?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  interests?:
    | {
        name: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  skills?:
    | {
        category: 'languages' | 'backend-apis' | 'data-storage' | 'infrastructure' | 'observability' | 'tools';
        items: {
          name: string;
          proficiency?: string | null;
          icon?: string | null;
          link?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  /**
   * Milliseconds between automatic panel changes.
   */
  carouselRotationInterval: number;
  /**
   * Optional ordered override. Leave empty to use featured projects.
   */
  featuredProjectOverride?: (number | Project)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-settings_select".
 */
export interface PortfolioSettingsSelect<T extends boolean = true> {
  heroCommand?: T;
  heroHeadline?: T;
  heroDescription?: T;
  resumeFile?: T;
  contact?:
    | T
    | {
        email?: T;
        intro?: T;
        socials?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
      };
  interests?:
    | T
    | {
        name?: T;
        description?: T;
        id?: T;
      };
  skills?:
    | T
    | {
        category?: T;
        items?:
          | T
          | {
              name?: T;
              proficiency?: T;
              icon?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  carouselRotationInterval?: T;
  featuredProjectOverride?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncTrackedRepositories".
 */
export interface TaskSyncTrackedRepositories {
  input: {
    repositoryId?: number | null;
    force?: boolean | null;
  };
  output: {
    cached: number;
    contributionsCreated: number;
    contributionsUpdated: number;
    failed: number;
    repositoriesSynced: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}